FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /CineApi

COPY CineApi/CineApi.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /CineApi
EXPOSE 7103

COPY --from=build /CineApi/publish .

ENTRYPOINT ["dotnet", "CineApi.dll"]